<?php
// $Id: swfobject_api.module,v 1.2.2.20.2.1 2008/10/29 02:38:35 arthuregg Exp $

/**
 * @file
 * Integrates the SWFObject Javascript library, allowing you to easily
 * embed flash in your website.
 *
 * Please see the README.txt file for more information on this module.
 */

/**
 * Implementation of hook_help().
 */
function swfobject_api_help($path, $arg) {
  switch ($path) {
    case 'admin/help#swfobject_api':
    case 'admin/settings/swfobject_api':
      return t('This module creates an API for flash content generation in pages based on the swfObject library. For more information, visit <a href="http://code.google.com/p/swfobject/">http://code.google.com/p/swfobject/</a>.');
    break;
  }
}

/**
 * Implementation of hook_perm().
 */
function swfobject_api_perm() {
  return array('administer swfobject');
}

/**
 * Implementation of hook_menu().
 */
function swfobject_api_menu() {
  $items = array();
  $items['admin/settings/swfobject_api'] = array(
    'title' => 'SWFObject API',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('swfobject_api_settings_form'),
    'access arguments' => array('administer swfobject'),
  );
  return $items;
}

/**
 * Menu callback: SWFObject API configuration form.
 */
function swfobject_api_settings_form() {
  $form = array();

  $form['swfobject_api_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Settings'),
    '#tree' => TRUE,
  );
  $form['swfobject_api_settings']['swfoa_version'] = array(
    '#type' => 'textfield',
    '#title' => t('Default minimum version required'),
    '#description' => t('This value can be overridden via the theme call.'),
    '#default_value' => variable_get('swfoa_express', '6'),
    '#required' => TRUE,
  );
  $form['swfobject_api_settings']['swfoa_express'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable express install.'),
    '#description' => t('Express install allows player upgrades without having to leave the site. Only versions 6.0.65 and above are supported.'),
    '#default_value' => variable_get('swfoa_express', FALSE),
  );
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save settings'));

  return system_settings_form($form);
}

/**
 * Implementation of hook_theme().
 */
function swfobject_api_theme() {
  return array(
    'swfobject_api' => array(
      'arguments' => array(
        'url' => NULL,
        'params' => NULL,
        'vars' => NULL,
        'id' => NULL,
        'attributes' => NULL
      )
    )
  );
}

/**
 * Theme function to add a flash file to the page.
 * 
 * The actual returned HTML from this function is minimal.  Its main effect is
 * side effects to setup the Javascript properly.
 * 
 * @ingroup themeable
 * @param $url 
 *   A web accessible url to the flash file.
 * @param $params 
 *   An associative array of parameters that describe the SWF.
 * @param $vars 
 *   An associative array of variables to pass through to the SWF flashvars value.
 * @param $id 
 *   An id to appened to the so object.
 * @param $attributes 
 *   Associative array of attributes to apply to the resulting flash tag (embed, object, etc.)
 */
function theme_swfobject_api($url, $params = array(), $vars = array(), $id = NULL, $attributes = array()) {
  static $swfobject_id = 1;

  _swfobject_api_ensure_swfobject();
 
  // Build the base params.
  $base_params = array(
    'width' => '100%',
    'height' => '100%',
    'no_flash' => t('Sorry, you need to install flash to see this content.'),
    'version' => variable_get('swfoa_version', '6'),
    'type' => 'movie',
    'bg_color' => '#FFFFFF',
    'express_redirect' => variable_get('swfoa_express', TRUE) ? drupal_get_path('module', 'swfobject_api') .'/expressinstall.swf' : 'false',
    'class' => '',
  );

  // Merge in default parameters.
  $params += $base_params;

  $div_id = empty($id) ? 'swfobject-'. $swfobject_id++ : $id;
  
  $height = $params['height'];
  $width = $params['width'];
  $express_redirect = $params['express_redirect'];
  $version = $params['version'];
  $bg_color = $params['bg_color'];
  $no_flash = $params['no_flash'];
  $class = implode(' ', array($params['class'], 'swfobject'));
  unset($params['height'], $params['width'], $params['express_redirect'], $params['version'], $params['bg_color'], $params['no_flash'], $params['class']);
  
  $settings['swfobject_api']['files'][$div_id] = array(
    'url' => $url,
    'params' => $params,
    'flashVars' => $vars,
    'attributes' => $attributes,
    'height' => $height,
    'width' => $width,
    'express_redirect' => $express_redirect,
    'version' => $version,
    'bg_color' => $bg_color,
  );
  
  drupal_add_js($settings, 'setting', 'footer', FALSE, TRUE, FALSE);

  // Return the placeholder HTML that will normally get 
  // replaced with flash content.
  return "<div id=\"$div_id\" class=\"{$class}\">{$no_flash}</div>\n";
}

/**
 * Ensure that the necessary JS files are loaded.
 * 
 * This function automatically checks to make sure that the JS files are only
 * loaded once.
 */
function _swfobject_api_ensure_swfobject() {
  static $done = FALSE;
  
  if ($done) {
    return;
  }
  
  // Load the swfobject library and our add-on to activate it.
  drupal_add_js(drupal_get_path('module', 'swfobject_api') .'/swfobject.js', 'module', 'footer');
  drupal_add_js(drupal_get_path('module', 'swfobject_api') .'/swfobject_api.js', 'module', 'footer');

  $done = TRUE;
}
